### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ofw** [GoogleCloudPlatform/cloud-spanner-emulator#90]
I'm using `v1.4.7` version.

Full log:

```sh
docker build . -t emulator -f build/docker/Dockerfile.ubuntu

[+] Building 84.7s (12/16)
 => [internal] load build definition from Dockerfile.ubuntu                        0.0s
 => => transferring dockerfile: 44B                                                0.0s
 => [internal] load .dockerignore                                                  0.0s
 => => transferring context: 34B                                                   0.0s
 => [internal] load metadata for gcr.io/distroless/cc:latest                       0.8s
 => [internal] load metadata for gcr.io/cloud-spanner-emulator/bazel-ubuntu:5.2.0  0.9s
 => [internal] load build context                                                  0.0s
 => => transferring context: 27.25kB                                               0.0s
 => CACHED [stage-1 1/4] FROM gcr.io/distroless/cc@sha256:442431d783e435ff0954d2a  0.0s
 => [build 1/7] FROM gcr.io/cloud-spanner-emulator/bazel-ubuntu:5.2.0-18.04@sha25  0.0s
 => CACHED [build 2/7] RUN apt-get update && DEBIAN_FRONTEND="noninteractive"      0.0s
 => CACHED [build 3/7] RUN apt-get -qq install -y software-properties-common       0.0s
 => CACHED [build 4/7] RUN add-apt-repository ppa:ubuntu-toolchain-r/test          0.0s
 => CACHED [build 5/7] COPY . src/                                                 0.0s
 => ERROR [build 6/7] RUN cd src                                                  83.7s
------
 > [build 6/7] RUN cd src                                                                  &&     CC=/usr/bin/gcc CXX=/usr/bin/g++                                               bazel build -c opt ...:
#12 0.241 Extracting Bazel installation...
#12 1.022 Starting local Bazel server and connecting to it...
#12 2.304 Loading:
#12 2.308 Loading: 0 packages loaded
#12 3.312 Loading: 0 packages loaded
#12 4.314 Loading: 0 packages loaded
#12 5.315 Loading: 0 packages loaded
#12 6.315 Loading: 0 packages loaded
#12 7.316 Loading: 0 packages loaded
#12 8.564 Loading: 0 packages loaded
#12 9.692 Loading: 0 packages loaded
#12 10.93 Loading: 0 packages loaded
#12 12.37 Loading: 0 packages loaded
#12 14.30 Loading: 0 packages loaded
#12 16.12 Loading: 0 packages loaded
#12 18.21 Loading: 0 packages loaded
#12 20.62 Loading: 0 packages loaded
#12 23.39 Loading: 0 packages loaded
#12 26.58 Loading: 0 packages loaded
#12 30.18 Analyzing: 241 targets (39 packages loaded, 0 targets configured)
#12 34.46 Analyzing: 241 targets (93 packages loaded, 45 targets configured)
#12 39.31 Analyzing: 241 targets (97 packages loaded, 78 targets configured)
#12 44.88 Analyzing: 241 targets (109 packages loaded, 935 targets configured)
#12 51.29 Analyzing: 241 targets (151 packages loaded, 10614 targets configured)
#12 58.52 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/base/BUILD:216:11: in cc_library rule @com_google_zetasql//zetasql/base:enum_utils: target '@com_google_zetasql//zetasql/base:enum_utils' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 58.66 Analyzing: 241 targets (188 packages loaded, 13485 targets configured)
#12 67.15 Analyzing: 241 targets (201 packages loaded, 17259 targets configured)
#12 67.34 WARNING: Download from https://mirror.bazel.build/github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
#12 68.94 WARNING: /src/tests/conformance/common/BUILD:21:11: in cc_library rule //tests/conformance/common:environment: target '//tests/conformance/common:environment' depends on deprecated target '@com_github_googleapis_google_cloud_cpp//google/cloud:google_cloud_cpp_common':
#12 68.94     This target is deprecated and will be removed on or after 2023-04-01. Use
#12 68.94     //:common instead. More info:
#12 68.94     https://github.com/googleapis/google-cloud-cpp/issues/3701
#12 68.94
#12 68.96 WARNING: /src/frontend/common/BUILD:100:11: in cc_library rule //frontend/common:status: target '//frontend/common:status' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 69.16 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/common/BUILD:218:11: in cc_library rule @com_google_zetasql//zetasql/common:proto_helper: target '@com_google_zetasql//zetasql/common:proto_helper' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 69.17 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/functions/BUILD:950:11: in cc_library rule @com_google_zetasql//zetasql/public/functions:common_proto: target '@com_google_zetasql//zetasql/public/functions:common_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.26 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/BUILD:1645:11: in cc_library rule @com_google_zetasql//zetasql/public:language_options: target '@com_google_zetasql//zetasql/public:language_options' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.28 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/types/BUILD:19:11: in cc_library rule @com_google_zetasql//zetasql/public/types:types: target '@com_google_zetasql//zetasql/public/types:types' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.29 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/BUILD:51:11: in cc_library rule @com_google_zetasql//zetasql/public:type: target '@com_google_zetasql//zetasql/public:type' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.31 WARNING: /src/tests/common/BUILD:135:11: in cc_library rule //tests/common:chunking: target '//tests/common:chunking' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.32 WARNING: /src/frontend/converters/BUILD:51:11: in cc_library rule //frontend/converters:chunking: target '//frontend/converters:chunking' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.33 WARNING: /src/frontend/converters/BUILD:149:11: in cc_library rule //frontend/converters:time: target '//frontend/converters:time' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.36 WARNING: /src/frontend/common/BUILD:53:11: in cc_library rule //frontend/common:protos: target '//frontend/common:protos' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.45 WARNING: /src/frontend/entities/BUILD:83:8: in cc_test rule //frontend/entities:instance_test: target '//frontend/entities:instance_test' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.48 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/BUILD:977:11: in cc_library rule @com_google_zetasql//zetasql/public:proto_value_conversion: target '@com_google_zetasql//zetasql/public:proto_value_conversion' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.49 WARNING: /src/frontend/converters/BUILD:253:11: in cc_library rule //frontend/converters:values: target '//frontend/converters:values' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.51 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/common/BUILD:356:11: in cc_library rule @com_google_zetasql//zetasql/common:builtin_function_internal: target '@com_google_zetasql//zetasql/common:builtin_function_internal' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.53 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/public/BUILD:192:11: in cc_library rule @com_google_zetasql//zetasql/public:simple_catalog: target '@com_google_zetasql//zetasql/public:simple_catalog' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.60 WARNING: /src/frontend/converters/BUILD:21:11: in cc_library rule //frontend/converters:keys: target '//frontend/converters:keys' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.62 WARNING: /src/frontend/converters/BUILD:179:11: in cc_library rule //frontend/converters:mutations: target '//frontend/converters:mutations' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.64 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/analyzer/BUILD:144:11: in cc_library rule @com_google_zetasql//zetasql/analyzer:resolver: target '@com_google_zetasql//zetasql/analyzer:resolver' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.67 WARNING: /src/frontend/converters/BUILD:91:11: in cc_library rule //frontend/converters:reads: target '//frontend/converters:reads' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.67 WARNING: /src/frontend/converters/BUILD:67:8: in cc_test rule //frontend/converters:chunking_test: target '//frontend/converters:chunking_test' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.73 WARNING: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/com_google_zetasql/zetasql/reference_impl/BUILD:141:11: in cc_library rule @com_google_zetasql//zetasql/reference_impl:evaluation: target '@com_google_zetasql//zetasql/reference_impl:evaluation' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.78 WARNING: /src/backend/query/BUILD:26:11: in cc_library rule //backend/query:query_engine: target '//backend/query:query_engine' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.82 WARNING: /src/frontend/converters/BUILD:286:11: in cc_library rule //frontend/converters:query: target '//frontend/converters:query' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.91 WARNING: /src/frontend/entities/BUILD:129:11: in cc_library rule //frontend/entities:transaction: target '//frontend/entities:transaction' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.94 WARNING: /src/frontend/handlers/BUILD:199:11: in cc_library rule //frontend/handlers:queries: target '//frontend/handlers:queries' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.94 WARNING: /src/frontend/handlers/BUILD:65:11: in cc_library rule //frontend/handlers:instances: target '//frontend/handlers:instances' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.99 WARNING: /src/frontend/handlers/BUILD:332:11: in cc_library rule //frontend/handlers:transactions: target '//frontend/handlers:transactions' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.99 WARNING: /src/frontend/handlers/BUILD:21:11: in cc_library rule //frontend/handlers:databases: target '//frontend/handlers:databases' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 71.99 WARNING: /src/frontend/handlers/BUILD:291:11: in cc_library rule //frontend/handlers:sessions: target '//frontend/handlers:sessions' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.00 WARNING: /src/frontend/handlers/BUILD:108:11: in cc_library rule //frontend/handlers:operations: target '//frontend/handlers:operations' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.00 WARNING: /src/frontend/handlers/BUILD:135:11: in cc_library rule //frontend/handlers:partitions: target '//frontend/handlers:partitions' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.00 WARNING: /src/frontend/server/BUILD:79:11: in cc_library rule //frontend/server:server: target '//frontend/server:server' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.01 WARNING: /src/tests/conformance/common/BUILD:34:11: in cc_library rule //tests/conformance/common:database_test_base: target '//tests/conformance/common:database_test_base' depends on deprecated target '@com_github_googleapis_google_cloud_cpp//google/cloud:google_cloud_cpp_common':
#12 72.01     This target is deprecated and will be removed on or after 2023-04-01. Use
#12 72.01     //:common instead. More info:
#12 72.01     https://github.com/googleapis/google-cloud-cpp/issues/3701
#12 72.01
#12 72.01 WARNING: /src/tests/conformance/cases/BUILD:21:11: in cc_library rule //tests/conformance/cases:cases: target '//tests/conformance/cases:cases' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.03 WARNING: /src/frontend/handlers/BUILD:87:8: in cc_test rule //frontend/handlers:instances_test: target '//frontend/handlers:instances_test' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.03 WARNING: /src/frontend/handlers/BUILD:43:8: in cc_test rule //frontend/handlers:databases_test: target '//frontend/handlers:databases_test' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 72.06 WARNING: /src/frontend/handlers/BUILD:313:8: in cc_test rule //frontend/handlers:sessions_test: target '//frontend/handlers:sessions_test' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
#12 76.88 Analyzing: 241 targets (224 packages loaded, 19265 targets configured)
#12 83.15 INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
#12 83.15   /src/WORKSPACE:116:21: in <toplevel>
#12 83.15   /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_gazelle/deps.bzl:75:24: in gazelle_dependencies
#12 83.15 Repository rule go_repository_tools defined at:
#12 83.15   /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
#12 83.17 ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
#12 83.17    Traceback (most recent call last):
#12 83.17 	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
#12 83.17 		fail("failed to build tools: " + result.stderr)
#12 83.17 Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
#12 83.17 ERROR: /src/WORKSPACE:116:21: fetching go_repository_tools rule //external:bazel_gazelle_go_repository_tools: Traceback (most recent call last):
#12 83.17 	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
#12 83.17 		fail("failed to build tools: " + result.stderr)
#12 83.17 Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
#12 83.28 ERROR: /src/gateway/BUILD:54:22: every rule of type generate_grpc_gateway_file implicitly depends upon the target '@grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway:protoc-gen-grpc-gateway', but this target could not be found because of: no such package '@grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
#12 83.49 ERROR: Analysis of target '//gateway:longrunning_operations_gateway_gen' failed; build aborted: Analysis failed
#12 83.55 INFO: Elapsed time: 83.212s
#12 83.55 INFO: 0 processes.
#12 83.55 FAILED: Build did NOT complete successfully (224 packages loaded, 19265 targets configured)
#12 83.56 FAILED: Build did NOT complete successfully (224 packages loaded, 19265 targets configured)
------
executor failed running [/bin/sh -c cd src                                                                  &&     CC=/usr/bin/gcc CXX=/usr/bin/g++                                               bazel build -c opt ...]: exit code: 1
```

**Comment by gauravsnj** [comment]
We've tried to build this version multiple times and didn't face any issue. Looking at the logs it most probably looks like some network issue that is not allowing you to download some dependencies. Can you retry this and if it fails again, you can reopen this issue with the docker version that you are using.
